[package]
name = "stock_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rust_decimal = "1.35"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"